version: '3.7'

services:
  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=bibin
      - POSTGRES_PASSWORD=bibin
      - POSTGRES_DB=reactmicro
    ports:
      - "5432:5432"
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  backend:
    volumes:
      - static:/static
    env_file:
      - .env
    build:
      context: ./backend
      dockerfile: docker/django/Dockerfile 
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./frontend
    volumes:
      - frontend:/app/build
  nginx:
    build:
      context: ./nginx
    volumes:
      - static:/static
      - frontend:/var/www/frontend
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
  celery:
    build: 
      context: ./backend
      dockerfile: docker/celery/Dockerfile
    depends_on:
      - db
      - redis
  celery-beat:
    build: 
      context: ./backend
      dockerfile: docker/celery-beat/Dockerfile
    depends_on:
      - celery
      - db
      - redis

volumes:
  static:
  frontend:


