# Generated by Django 4.2.7 on 2023-11-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
