# Generated by Django 4.2.7 on 2023-11-30 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpost', '0002_alter_posts_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='valid_till',
            field=models.DateTimeField(),
        ),
    ]
